import { neonSql } from '../db/neon';

export interface ResidentItem {
  id: string;
  propertyId: string;
  houseCode: string;
  areaLabel: string;
  fullName: string;
  relation: 'KEPALA_KELUARGA' | 'ISTRI' | 'ANAK' | 'ORANG_TUA' | 'FAMILI_LAIN' | 'ART' | 'PENYEWA';
  gender: 'LAKI_LAKI' | 'PEREMPUAN';
  birthPlaceDate: string;
  religion: string;
  occupation: string;
  phone: string;
  email: string;
  idCard: string;
  familyCard: string;
  domicileStatus: 'KTP_SETEMPAT' | 'KTP_LUAR_DAERAH' | 'SURAT_DOMISILI';
  bloodType: 'A' | 'B' | 'AB' | 'O';
  isEmergency: boolean;
  notes?: string;
}

export interface VehicleItem {
  id: string;
  propertyId: string;
  houseCode: string;
  areaLabel: string;
  ownerName: string;
  plateNumber: string;
  type: string;
  brand: string;
  model: string;
  year: number;
  color: string;
  rfidTag: string;
  gateAccess: string;
  rfidStatus: 'AKTIF' | 'DIBLOKIR' | 'PENDING_VERIFIKASI';
  notes?: string;
}

export interface PermitItem {
  id: string;
  propertyCode: string;
  houseCode: string;
  areaLabel: string;
  ownerName: string;
  workType: string;
  contractorName: string;
  contractorPhone: string;
  workersCount: number;
  workersList: string;
  startDate: string;
  endDate: string;
  allowedHours: string;
  depositStatus: string;
  depositAmount: number;
  description: string;
  status: 'APPROVED' | 'PENDING_REVIEW' | 'COMPLETED' | 'SUSPENDED';
  issuedAt: string;
}

export interface UtilityItem {
  id: string;
  propertyId: string;
  houseCode: string;
  areaLabel: string;
  ownerName: string;
  plnCapacity: string;
  electricityCapacity?: string;
  plnCustomerId: string;
  pamMeterNo: string;
  pamReadingLastMonth: number;
  pamReadingThisMonth: number;
  pamUsage: number;
  monthlyIplFee: number;
  wasteSchedule: string;
  hasBiopori: boolean;
  hasSolarPanel: boolean;
  paymentStatus: 'LUNAS' | 'MENUNGGU_BAYAR' | 'MENUNGGAK';
  notes?: string;
}

// 24 Sensus Penghuni Riil Grand Sariwangi (Kav A s/d Kav M)
export const DEFAULT_RESIDENTS: ResidentItem[] = [
  // Kav A - Pak Verial
  {
    id: 'res-kav-a-1',
    propertyId: 'prop-kav-a',
    houseCode: 'Kav A',
    areaLabel: 'Kavling',
    fullName: 'Pak Verial',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Bandung, 14-04-1984',
    religion: 'ISLAM',
    occupation: 'Senior IT Consultant',
    phone: '082316485044',
    email: 'verial@wargahub.id',
    idCard: '3204281404840001',
    familyCard: '3204281404840000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: true,
    notes: 'Penanggung jawab utama Kavling A. Siap dihubungi 24 jam.',
  },
  {
    id: 'res-kav-a-2',
    propertyId: 'prop-kav-a',
    houseCode: 'Kav A',
    areaLabel: 'Kavling',
    fullName: 'Bu Viny',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Jakarta, 22-09-1986',
    religion: 'ISLAM',
    occupation: 'Wiraswasta / Fashion Designer',
    phone: '082316485045',
    email: 'viny@wargahub.id',
    idCard: '3204286209860002',
    familyCard: '3204281404840000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'A',
    isEmergency: false,
    notes: 'Koordinator kegiatan senam & arisan ibu-ibu komplek.',
  },
  {
    id: 'res-kav-a-3',
    propertyId: 'prop-kav-a',
    houseCode: 'Kav A',
    areaLabel: 'Kavling',
    fullName: 'Kenzo Verial',
    relation: 'ANAK',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Bandung, 11-05-2015',
    religion: 'ISLAM',
    occupation: 'Pelajar SD',
    phone: '-',
    email: '-',
    idCard: '3204281105150003',
    familyCard: '3204281404840000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: false,
    notes: 'Siswa kelas 5 SD Al-Azhar Bandung.',
  },

  // Kav B - Mahasiswa Polban (Penyewa dari Bu Shinta)
  {
    id: 'res-kav-b-1',
    propertyId: 'prop-kav-b',
    houseCode: 'Kav B',
    areaLabel: 'Kavling',
    fullName: 'Mahasiswa Polban',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Cirebon, 19-08-2003',
    religion: 'ISLAM',
    occupation: 'Mahasiswa Teknik Komputer Polban',
    phone: '081220885100',
    email: 'polban.resident@wargahub.id',
    idCard: '3204281908030001',
    familyCard: '3204281908030000',
    domicileStatus: 'KTP_LUAR_DAERAH',
    bloodType: 'B',
    isEmergency: true,
    notes: 'Ketua sewa kontrakan mahasiswa Kav B. Pemilik: Bu Shinta.',
  },
  {
    id: 'res-kav-b-2',
    propertyId: 'prop-kav-b',
    houseCode: 'Kav B',
    areaLabel: 'Kavling',
    fullName: 'Rendy Aditya',
    relation: 'PENYEWA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Majalengka, 14-04-2002',
    religion: 'ISLAM',
    occupation: 'Mahasiswa Teknik Sipil Polban',
    phone: '081220885102',
    email: 'rendy.aditya@polban.ac.id',
    idCard: '3204281404020002',
    familyCard: '3204281404020000',
    domicileStatus: 'KTP_LUAR_DAERAH',
    bloodType: 'O',
    isEmergency: false,
    notes: 'Penyewa bersama Kav B.',
  },

  // Kav C - Bu Rina (Pemilik / Standby)
  {
    id: 'res-kav-c-1',
    propertyId: 'prop-kav-c',
    houseCode: 'Kav C',
    areaLabel: 'Kavling',
    fullName: 'Bu Rina',
    relation: 'KEPALA_KELUARGA',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Bandung, 15-09-1980',
    religion: 'ISLAM',
    occupation: 'Dosen / Peneliti ITB',
    phone: '087823964649',
    email: 'rina.kavc@wargahub.id',
    idCard: '3204285509800001',
    familyCard: '3204285509800000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'AB',
    isEmergency: true,
    notes: 'Pemilik Kav C, unit saat ini kosong / standby dinas.',
  },

  // Kav D - Pak Rieva
  {
    id: 'res-kav-d-1',
    propertyId: 'prop-kav-d',
    houseCode: 'Kav D',
    areaLabel: 'Kavling',
    fullName: 'Pak Rieva',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Bandung, 22-01-1982',
    religion: 'ISLAM',
    occupation: 'Senior Architecture Principal',
    phone: '081573007178',
    email: 'rieva@wargahub.id',
    idCard: '3204282201820001',
    familyCard: '3204282201820000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: true,
    notes: 'Penanggung jawab renovasi kanopi & fasad Kav D.',
  },
  {
    id: 'res-kav-d-2',
    propertyId: 'prop-kav-d',
    houseCode: 'Kav D',
    areaLabel: 'Kavling',
    fullName: 'Bu Sarah Rieva',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Surabaya, 10-03-1984',
    religion: 'ISLAM',
    occupation: 'Interior Designer',
    phone: '081573007179',
    email: 'sarah.rieva@wargahub.id',
    idCard: '3204285003840002',
    familyCard: '3204282201820000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'A',
    isEmergency: false,
    notes: 'Pendamping keluarga Kav D.',
  },

  // Kav E - Pak Budi & Bu Endang
  {
    id: 'res-kav-e-1',
    propertyId: 'prop-kav-e',
    houseCode: 'Kav E',
    areaLabel: 'Kavling',
    fullName: 'Pak Budi Santoso',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Semarang, 12-03-1985',
    religion: 'ISLAM',
    occupation: 'General Manager Logistik',
    phone: '0811238689',
    email: 'budi.santoso@wargahub.id',
    idCard: '3204281203850001',
    familyCard: '3204281203850000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'B',
    isEmergency: true,
    notes: 'Status iuran IPL Oktober 2026: LUNAS.',
  },
  {
    id: 'res-kav-e-2',
    propertyId: 'prop-kav-e',
    houseCode: 'Kav E',
    areaLabel: 'Kavling',
    fullName: 'Bu Endang',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Solo, 24-08-1986',
    religion: 'ISLAM',
    occupation: 'Wiraswasta Kuliner',
    phone: '0811238690',
    email: 'endang.budi@wargahub.id',
    idCard: '3204286408860002',
    familyCard: '3204281203850000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'B',
    isEmergency: false,
    notes: 'Pengurus bendahara arisan blok.',
  },
  {
    id: 'res-kav-e-3',
    propertyId: 'prop-kav-e',
    houseCode: 'Kav E',
    areaLabel: 'Kavling',
    fullName: 'Dimas Santoso',
    relation: 'ANAK',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Bandung, 19-09-2012',
    religion: 'ISLAM',
    occupation: 'Pelajar SMP',
    phone: '-',
    email: '-',
    idCard: '3204281909120003',
    familyCard: '3204281203850000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'B',
    isEmergency: false,
    notes: 'Siswa kelas 8 SMP.',
  },

  // Kav F - Pa Anggia (Penyewa dari Pak Adi)
  {
    id: 'res-kav-f-1',
    propertyId: 'prop-kav-f',
    houseCode: 'Kav F',
    areaLabel: 'Kavling',
    fullName: 'Pa Anggia',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Bandung, 18-04-1983',
    religion: 'ISLAM',
    occupation: 'IT Security Specialist',
    phone: '081220082240',
    email: 'anggia@wargahub.id',
    idCard: '3204281804830001',
    familyCard: '3204281804830000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: true,
    notes: 'Kepala keluarga penyewa Kav F. Pemilik: Pak Adi/Bu Ratih.',
  },
  {
    id: 'res-kav-f-2',
    propertyId: 'prop-kav-f',
    houseCode: 'Kav F',
    areaLabel: 'Kavling',
    fullName: 'Bu Rina Anggia',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Bogor, 25-10-1985',
    religion: 'ISLAM',
    occupation: 'Akuntan Publik',
    phone: '081220082241',
    email: 'rina.anggia@wargahub.id',
    idCard: '3204286510850002',
    familyCard: '3204281804830000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'A',
    isEmergency: false,
    notes: 'Istri Pa Anggia.',
  },

  // Kav G - Pak Misael & Bu Caroline
  {
    id: 'res-kav-g-1',
    propertyId: 'prop-kav-g',
    houseCode: 'Kav G',
    areaLabel: 'Kavling',
    fullName: 'Pak Misael',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Bandung, 14-06-1988',
    religion: 'KRISTEN',
    occupation: 'Senior Business Analyst',
    phone: '082216668852',
    email: 'misael@wargahub.id',
    idCard: '3204281406880001',
    familyCard: '3204281406880000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'A',
    isEmergency: true,
    notes: 'Kepala keluarga Kav G.',
  },
  {
    id: 'res-kav-g-2',
    propertyId: 'prop-kav-g',
    houseCode: 'Kav G',
    areaLabel: 'Kavling',
    fullName: 'Bu Caroline',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Manado, 11-02-1990',
    religion: 'KRISTEN',
    occupation: 'Dokter Umum RS Advent',
    phone: '082216668853',
    email: 'caroline@wargahub.id',
    idCard: '3204285102900002',
    familyCard: '3204281406880000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'AB',
    isEmergency: true,
    notes: 'Tenaga medis prioritas lingkungan komplek bila keadaan darurat.',
  },

  // Kav H - Pak Fahmi Rizal
  {
    id: 'res-kav-h-1',
    propertyId: 'prop-kav-h',
    houseCode: 'Kav H',
    areaLabel: 'Kavling',
    fullName: 'Pak Fahmi Rizal',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Cimahi, 05-11-1981',
    religion: 'ISLAM',
    occupation: 'Senior Mechanical Engineer',
    phone: '085781217072',
    email: 'fahmi.rizal@wargahub.id',
    idCard: '3204280511810001',
    familyCard: '3204280511810000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: true,
    notes: 'Kepala keluarga Kav H.',
  },
  {
    id: 'res-kav-h-2',
    propertyId: 'prop-kav-h',
    houseCode: 'Kav H',
    areaLabel: 'Kavling',
    fullName: 'Bu Nisa Rizal',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Garut, 18-12-1984',
    religion: 'ISLAM',
    occupation: 'Guru SMA Negeri',
    phone: '085781217073',
    email: 'nisa.rizal@wargahub.id',
    idCard: '3204285812840002',
    familyCard: '3204280511810000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'B',
    isEmergency: false,
    notes: 'Istri Pak Fahmi.',
  },

  // Kav I - Pak Yahya (Penyewa dari Bu Hj Yatti)
  {
    id: 'res-kav-i-1',
    propertyId: 'prop-kav-i',
    houseCode: 'Kav I',
    areaLabel: 'Kavling',
    fullName: 'Pak Yahya',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Sukabumi, 25-02-1993',
    religion: 'ISLAM',
    occupation: 'Lead Software Engineer',
    phone: '085722003303',
    email: 'yahya@wargahub.id',
    idCard: '3204282502930001',
    familyCard: '3204282502930000',
    domicileStatus: 'KTP_LUAR_DAERAH',
    bloodType: 'O',
    isEmergency: true,
    notes: 'Penyewa aktif Kav I. Pemilik: Bu Hj Yatti.',
  },
  {
    id: 'res-kav-i-2',
    propertyId: 'prop-kav-i',
    houseCode: 'Kav I',
    areaLabel: 'Kavling',
    fullName: 'Bu Salma',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Bandung, 16-08-1995',
    religion: 'ISLAM',
    occupation: 'Product UI Designer',
    phone: '085722003304',
    email: 'salma@wargahub.id',
    idCard: '3204285608950002',
    familyCard: '3204282502930000',
    domicileStatus: 'KTP_LUAR_DAERAH',
    bloodType: 'A',
    isEmergency: false,
    notes: 'Istri Pak Yahya.',
  },

  // Kav J - Bu Sofia P (Pemilik / Standby)
  {
    id: 'res-kav-j-1',
    propertyId: 'prop-kav-j',
    houseCode: 'Kav J',
    areaLabel: 'Kavling',
    fullName: 'Bu Sofia P',
    relation: 'KEPALA_KELUARGA',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Jakarta, 07-05-1979',
    religion: 'ISLAM',
    occupation: 'Notaris & PPAT',
    phone: '08170248889',
    email: 'sofia.p@wargahub.id',
    idCard: '3204284705790001',
    familyCard: '3204284705790000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: true,
    notes: 'Pemilik Kav J, renovasi interior dapur telah selesai (Agustus 2026).',
  },

  // Kav K - Pak Eky & Bu Winda
  {
    id: 'res-kav-k-1',
    propertyId: 'prop-kav-k',
    houseCode: 'Kav K',
    areaLabel: 'Kavling',
    fullName: 'Pak Eky',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Bandung, 17-03-1986',
    religion: 'ISLAM',
    occupation: 'Konsultan Manajemen Bisnis',
    phone: '08993949392',
    email: 'eky@wargahub.id',
    idCard: '3204281703860001',
    familyCard: '3204281703860000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'B',
    isEmergency: true,
    notes: 'Kepala keluarga Kav K.',
  },
  {
    id: 'res-kav-k-2',
    propertyId: 'prop-kav-k',
    houseCode: 'Kav K',
    areaLabel: 'Kavling',
    fullName: 'Bu Winda',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Bandung, 19-06-1989',
    religion: 'ISLAM',
    occupation: 'Dosen Universitas Padjadjaran',
    phone: '08993949393',
    email: 'winda@wargahub.id',
    idCard: '3204285906890002',
    familyCard: '3204281703860000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: false,
    notes: 'Istri Pak Eky.',
  },

  // Kav L - Pak Haji Ano & Bu Hj Euis
  {
    id: 'res-kav-l-1',
    propertyId: 'prop-kav-l',
    houseCode: 'Kav L',
    areaLabel: 'Kavling',
    fullName: 'Pak Haji Ano',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Tasikmalaya, 10-01-1960',
    religion: 'ISLAM',
    occupation: 'Tokoh Warga / Pensiunan BUMN',
    phone: '08112335353',
    email: 'haji.ano@wargahub.id',
    idCard: '3204281001600001',
    familyCard: '3204281001600000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: true,
    notes: 'Sesepuh & Penasehat Paguyuban Warga Grand Sariwangi.',
  },
  {
    id: 'res-kav-l-2',
    propertyId: 'prop-kav-l',
    houseCode: 'Kav L',
    areaLabel: 'Kavling',
    fullName: 'Bu Hj Euis',
    relation: 'ISTRI',
    gender: 'PEREMPUAN',
    birthPlaceDate: 'Tasikmalaya, 11-04-1964',
    religion: 'ISLAM',
    occupation: 'Ibu Rumah Tangga',
    phone: '08112335354',
    email: 'hj.euis@wargahub.id',
    idCard: '3204285104640002',
    familyCard: '3204281001600000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'O',
    isEmergency: false,
    notes: 'Istri Pak Haji Ano.',
  },

  // Kav M - Pak Dedi N (Pemilik / Standby)
  {
    id: 'res-kav-m-1',
    propertyId: 'prop-kav-m',
    houseCode: 'Kav M',
    areaLabel: 'Kavling',
    fullName: 'Pak Dedi N',
    relation: 'KEPALA_KELUARGA',
    gender: 'LAKI_LAKI',
    birthPlaceDate: 'Bandung, 09-07-1972',
    religion: 'ISLAM',
    occupation: 'Direktur Kontraktor Konstruksi',
    phone: '081220022407',
    email: 'dedi.jaya@wargahub.id',
    idCard: '3204280907720001',
    familyCard: '3204280907720000',
    domicileStatus: 'KTP_SETEMPAT',
    bloodType: 'A',
    isEmergency: true,
    notes: 'Pemilik Kav M (Pak Dedi N / Pak Jaya). Unit standby siap huni.',
  },
];

// 12 Kendaraan & Tag RFID Grand Sariwangi
export const DEFAULT_VEHICLES: VehicleItem[] = [
  {
    id: 'veh-kav-a-1',
    propertyId: 'prop-kav-a',
    houseCode: 'Kav A',
    areaLabel: 'Kavling',
    ownerName: 'Pak Verial',
    plateNumber: 'D 1234 VRL',
    type: 'Mobil',
    brand: 'Toyota',
    model: 'Innova Zenix 2.0 Hybrid',
    year: 2023,
    color: 'Hitam Metalik',
    rfidTag: 'RFID-7821001',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Parkir di carport dalam kavling.',
  },
  {
    id: 'veh-kav-a-2',
    propertyId: 'prop-kav-a',
    houseCode: 'Kav A',
    areaLabel: 'Kavling',
    ownerName: 'Pak Verial',
    plateNumber: 'D 4321 VR',
    type: 'Motor',
    brand: 'Honda',
    model: 'PCX 160 ABS',
    year: 2022,
    color: 'Putih Mutiara',
    rfidTag: 'RFID-7821002',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Stiker RFID windshield terpasang.',
  },
  {
    id: 'veh-kav-b-1',
    propertyId: 'prop-kav-b',
    houseCode: 'Kav B',
    areaLabel: 'Kavling',
    ownerName: 'Mahasiswa Polban',
    plateNumber: 'D 8851 SHT',
    type: 'Mobil',
    brand: 'Toyota',
    model: 'Yaris Cross 1.5 GR',
    year: 2024,
    color: 'Merah Marun',
    rfidTag: 'RFID-7821003',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Kendaraan operasional penyewa Kav B.',
  },
  {
    id: 'veh-kav-d-1',
    propertyId: 'prop-kav-d',
    houseCode: 'Kav D',
    areaLabel: 'Kavling',
    ownerName: 'Pak Rieva',
    plateNumber: 'D 1573 RV',
    type: 'Mobil',
    brand: 'Honda',
    model: 'CR-V Turbo Prestige',
    year: 2021,
    color: 'Abu-abu Metalik',
    rfidTag: 'RFID-7821004',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Parkir garasi Kavling D.',
  },
  {
    id: 'veh-kav-e-1',
    propertyId: 'prop-kav-e',
    houseCode: 'Kav E',
    areaLabel: 'Kavling',
    ownerName: 'Pak Budi',
    plateNumber: 'D 1189 BD',
    type: 'Mobil',
    brand: 'Honda',
    model: 'HR-V 1.5 SE',
    year: 2023,
    color: 'Putih Pearl',
    rfidTag: 'RFID-7821005',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Mobil utama keluarga Pak Budi.',
  },
  {
    id: 'veh-kav-e-2',
    propertyId: 'prop-kav-e',
    houseCode: 'Kav E',
    areaLabel: 'Kavling',
    ownerName: 'Pak Budi',
    plateNumber: 'D 5542 EB',
    type: 'Motor',
    brand: 'Yamaha',
    model: 'NMAX 155 Connected',
    year: 2022,
    color: 'Biru Matte',
    rfidTag: 'RFID-7821006',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Sepeda motor harian.',
  },
  {
    id: 'veh-kav-f-1',
    propertyId: 'prop-kav-f',
    houseCode: 'Kav F',
    areaLabel: 'Kavling',
    ownerName: 'Pa Anggia',
    plateNumber: 'D 1822 AG',
    type: 'Mobil',
    brand: 'Toyota',
    model: 'All New Veloz Q CVT',
    year: 2022,
    color: 'Silver Mica',
    rfidTag: 'RFID-7821007',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Mobil operasional penyewa Kav F.',
  },
  {
    id: 'veh-kav-g-1',
    propertyId: 'prop-kav-g',
    houseCode: 'Kav G',
    areaLabel: 'Kavling',
    ownerName: 'Pak Misael',
    plateNumber: 'D 1666 MS',
    type: 'Mobil',
    brand: 'Mitsubishi',
    model: 'Xpander Ultimate',
    year: 2023,
    color: 'Hitam Metalik',
    rfidTag: 'RFID-7821008',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Parkir carport Kav G.',
  },
  {
    id: 'veh-kav-h-1',
    propertyId: 'prop-kav-h',
    houseCode: 'Kav H',
    areaLabel: 'Kavling',
    ownerName: 'Pak Fahmi Rizal',
    plateNumber: 'D 1072 FZ',
    type: 'Mobil',
    brand: 'Suzuki',
    model: 'All New Ertiga Hybrid',
    year: 2023,
    color: 'Abu-abu Metalik',
    rfidTag: 'RFID-7821009',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Kendaraan keluarga Kav H.',
  },
  {
    id: 'veh-kav-i-1',
    propertyId: 'prop-kav-i',
    houseCode: 'Kav I',
    areaLabel: 'Kavling',
    ownerName: 'Pak Yahya',
    plateNumber: 'D 3303 YH',
    type: 'Mobil',
    brand: 'Honda',
    model: 'Brio RS Urbanite',
    year: 2022,
    color: 'Kuning Carnation',
    rfidTag: 'RFID-7821010',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Kendaraan operasional penyewa Kav I.',
  },
  {
    id: 'veh-kav-k-1',
    propertyId: 'prop-kav-k',
    houseCode: 'Kav K',
    areaLabel: 'Kavling',
    ownerName: 'Pak Eky',
    plateNumber: 'D 1949 EK',
    type: 'Mobil',
    brand: 'Daihatsu',
    model: 'Rocky 1.0 Turbo',
    year: 2022,
    color: 'Putih Solid',
    rfidTag: 'RFID-7821011',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Parkir di carport dalam kavling.',
  },
  {
    id: 'veh-kav-l-1',
    propertyId: 'prop-kav-l',
    houseCode: 'Kav L',
    areaLabel: 'Kavling',
    ownerName: 'Pak Haji Ano',
    plateNumber: 'D 1353 AN',
    type: 'Mobil',
    brand: 'Toyota',
    model: 'Fortuner 2.8 GR Sport',
    year: 2022,
    color: 'Hitam Metalik',
    rfidTag: 'RFID-7821012',
    gateAccess: 'SEMUA_GERBANG',
    rfidStatus: 'AKTIF',
    notes: 'Kendaraan pribadi Pak Haji Ano.',
  },
];

// 4 Izin Renovasi & Pekerja Proyek Riil Grand Sariwangi
export const DEFAULT_PERMITS: PermitItem[] = [
  {
    id: 'PERMIT-KAV-D-01',
    propertyCode: 'Kav D',
    houseCode: 'Kav D',
    areaLabel: 'Kavling',
    ownerName: 'Pak Rieva',
    workType: 'Pengecatan & Kanopi',
    contractorName: 'Mandor Kang Asep',
    contractorPhone: '0812-3344-5566',
    workersCount: 3,
    workersList: 'Kang Asep (Mandor), Jajang, Dadan',
    startDate: '2026-09-01',
    endDate: '2026-10-15',
    allowedHours: '08:00 - 17:00 WIB (Senin - Sabtu)',
    depositStatus: 'DEPOSIT_PAID',
    depositAmount: 1000000,
    description: 'Pemasangan kanopi alderon carport dan pengecatan ulang tampak depan rumah Kav D.',
    status: 'APPROVED',
    issuedAt: '2026-08-28T09:00:00.000Z',
  },
  {
    id: 'PERMIT-KAV-G-01',
    propertyCode: 'Kav G',
    houseCode: 'Kav G',
    areaLabel: 'Kavling',
    ownerName: 'Pak Misael',
    workType: 'Perbaikan Atap & Talang Air',
    contractorName: 'Mandor Pak Ujang',
    contractorPhone: '0813-8899-7711',
    workersCount: 2,
    workersList: 'Pak Ujang (Mandor), Wawan',
    startDate: '2026-09-20',
    endDate: '2026-10-05',
    allowedHours: '08:30 - 16:30 WIB (Senin - Sabtu)',
    depositStatus: 'DEPOSIT_PAID',
    depositAmount: 500000,
    description: 'Waterproofing dak talang air sisi timur dan perbaikan genteng bocor sebelum musim hujan.',
    status: 'APPROVED',
    issuedAt: '2026-09-18T10:30:00.000Z',
  },
  {
    id: 'PERMIT-KAV-B-01',
    propertyCode: 'Kav B',
    houseCode: 'Kav B',
    areaLabel: 'Kavling',
    ownerName: 'Mahasiswa Polban',
    workType: 'Pemasangan Teralis Jendela Belakang',
    contractorName: 'Bengkel Las Berkah Jaya',
    contractorPhone: '0819-2233-4455',
    workersCount: 2,
    workersList: 'Pak Iman, Solihin',
    startDate: '2026-09-28',
    endDate: '2026-10-08',
    allowedHours: '09:00 - 16:00 WIB (Senin - Sabtu)',
    depositStatus: 'DEPOSIT_PAID',
    depositAmount: 300000,
    description: 'Pemasangan teralis besi hollow galvanis untuk keamanan jendela lantai 1 atas persetujuan Bu Shinta.',
    status: 'APPROVED',
    issuedAt: '2026-09-26T14:15:00.000Z',
  },
  {
    id: 'PERMIT-KAV-J-01',
    propertyCode: 'Kav J',
    houseCode: 'Kav J',
    areaLabel: 'Kavling',
    ownerName: 'Bu Sofia P',
    workType: 'Renovasi Interior & Dapur',
    contractorName: 'CV Rapi Mandiri Interior',
    contractorPhone: '0811-9988-7766',
    workersCount: 4,
    workersList: 'Pak Hendra (Mandor), Yana, Agus, Maman',
    startDate: '2026-08-01',
    endDate: '2026-08-30',
    allowedHours: '08:00 - 17:00 WIB (Senin - Sabtu)',
    depositStatus: 'DEPOSIT_REFUNDED',
    depositAmount: 1500000,
    description: 'Pekerjaan kitchen set minimalis dan instalasi exhaust fan dapur selesai rapi tanpa keluhan warga.',
    status: 'COMPLETED',
    issuedAt: '2026-07-28T11:00:00.000Z',
  },
];

// 13 Catatan Utilitas Mandiri & Meteran Grand Sariwangi (Kav A s/d Kav M)
export const DEFAULT_UTILITIES: UtilityItem[] = [
  {
    id: 'UTIL-KAV-A',
    propertyId: 'prop-kav-a',
    houseCode: 'Kav A',
    areaLabel: 'Kavling',
    ownerName: 'Pak Verial',
    plnCapacity: '3.500 VA',
    plnCustomerId: 'PLN-538812001',
    pamMeterNo: 'PAM-88301',
    pamReadingLastMonth: 135,
    pamReadingThisMonth: 154,
    pamUsage: 19,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Meteran PAM digital, tidak ada kebocoran pipa.',
  },
  {
    id: 'UTIL-KAV-B',
    propertyId: 'prop-kav-b',
    houseCode: 'Kav B',
    areaLabel: 'Kavling',
    ownerName: 'Mahasiswa Polban',
    plnCapacity: '2.200 VA',
    plnCustomerId: 'PLN-538812002',
    pamMeterNo: 'PAM-88302',
    pamReadingLastMonth: 120,
    pamReadingThisMonth: 138,
    pamUsage: 18,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Pemakaian normal penghuni kos/kontrak.',
  },
  {
    id: 'UTIL-KAV-C',
    propertyId: 'prop-kav-c',
    houseCode: 'Kav C',
    areaLabel: 'Kavling',
    ownerName: 'Bu Rina',
    plnCapacity: '2.200 VA',
    plnCustomerId: 'PLN-538812003',
    pamMeterNo: 'PAM-88303',
    pamReadingLastMonth: 45,
    pamReadingThisMonth: 46,
    pamUsage: 1,
    monthlyIplFee: 200000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Unit kosong standby, tarif pemeliharaan kebersihan rutin.',
  },
  {
    id: 'UTIL-KAV-D',
    propertyId: 'prop-kav-d',
    houseCode: 'Kav D',
    areaLabel: 'Kavling',
    ownerName: 'Pak Rieva',
    plnCapacity: '3.500 VA',
    plnCustomerId: 'PLN-538812004',
    pamMeterNo: 'PAM-88304',
    pamReadingLastMonth: 142,
    pamReadingThisMonth: 163,
    pamUsage: 21,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: true,
    paymentStatus: 'LUNAS',
    notes: 'Solar panel on-grid 2.2 kWp terpasang di atap dak.',
  },
  {
    id: 'UTIL-KAV-E',
    propertyId: 'prop-kav-e',
    houseCode: 'Kav E',
    areaLabel: 'Kavling',
    ownerName: 'Pak Budi',
    plnCapacity: '3.500 VA',
    plnCustomerId: 'PLN-538812005',
    pamMeterNo: 'PAM-88305',
    pamReadingLastMonth: 130,
    pamReadingThisMonth: 152,
    pamUsage: 22,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Iuran IPL Oktober 2026 LUNAS tercatat.',
  },
  {
    id: 'UTIL-KAV-F',
    propertyId: 'prop-kav-f',
    houseCode: 'Kav F',
    areaLabel: 'Kavling',
    ownerName: 'Pa Anggia',
    plnCapacity: '2.200 VA',
    plnCustomerId: 'PLN-538812006',
    pamMeterNo: 'PAM-88306',
    pamReadingLastMonth: 110,
    pamReadingThisMonth: 126,
    pamUsage: 16,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Penyewa Pa Anggia membayar tepat waktu.',
  },
  {
    id: 'UTIL-KAV-G',
    propertyId: 'prop-kav-g',
    houseCode: 'Kav G',
    areaLabel: 'Kavling',
    ownerName: 'Pak Misael',
    plnCapacity: '3.500 VA',
    plnCustomerId: 'PLN-538812007',
    pamMeterNo: 'PAM-88307',
    pamReadingLastMonth: 125,
    pamReadingThisMonth: 142,
    pamUsage: 17,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Terdapat 2 lubang biopori di halaman samping.',
  },
  {
    id: 'UTIL-KAV-H',
    propertyId: 'prop-kav-h',
    houseCode: 'Kav H',
    areaLabel: 'Kavling',
    ownerName: 'Pak Fahmi Rizal',
    plnCapacity: '2.200 VA',
    plnCustomerId: 'PLN-538812008',
    pamMeterNo: 'PAM-88308',
    pamReadingLastMonth: 115,
    pamReadingThisMonth: 131,
    pamUsage: 16,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Meteran PAM analog berfungsi akurat.',
  },
  {
    id: 'UTIL-KAV-I',
    propertyId: 'prop-kav-i',
    houseCode: 'Kav I',
    areaLabel: 'Kavling',
    ownerName: 'Pak Yahya',
    plnCapacity: '2.200 VA',
    plnCustomerId: 'PLN-538812009',
    pamMeterNo: 'PAM-88309',
    pamReadingLastMonth: 108,
    pamReadingThisMonth: 123,
    pamUsage: 15,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Penyewa Pak Yahya, iuran tertib.',
  },
  {
    id: 'UTIL-KAV-J',
    propertyId: 'prop-kav-j',
    houseCode: 'Kav J',
    areaLabel: 'Kavling',
    ownerName: 'Bu Sofia P',
    plnCapacity: '2.200 VA',
    plnCustomerId: 'PLN-538812010',
    pamMeterNo: 'PAM-88310',
    pamReadingLastMonth: 50,
    pamReadingThisMonth: 51,
    pamUsage: 1,
    monthlyIplFee: 200000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Unit kosong standby, iuran kebersihan rutin lunas.',
  },
  {
    id: 'UTIL-KAV-K',
    propertyId: 'prop-kav-k',
    houseCode: 'Kav K',
    areaLabel: 'Kavling',
    ownerName: 'Pak Eky',
    plnCapacity: '3.500 VA',
    plnCustomerId: 'PLN-538812011',
    pamMeterNo: 'PAM-88311',
    pamReadingLastMonth: 128,
    pamReadingThisMonth: 146,
    pamUsage: 18,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Pemakaian normal keluarga 2 jiwa.',
  },
  {
    id: 'UTIL-KAV-L',
    propertyId: 'prop-kav-l',
    houseCode: 'Kav L',
    areaLabel: 'Kavling',
    ownerName: 'Pak Haji Ano',
    plnCapacity: '3.500 VA',
    plnCustomerId: 'PLN-538812012',
    pamMeterNo: 'PAM-88312',
    pamReadingLastMonth: 138,
    pamReadingThisMonth: 158,
    pamUsage: 20,
    monthlyIplFee: 250000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Rumah tokoh warga, instalasi listrik & air sangat terawat.',
  },
  {
    id: 'UTIL-KAV-M',
    propertyId: 'prop-kav-m',
    houseCode: 'Kav M',
    areaLabel: 'Kavling',
    ownerName: 'Pak Dedi N',
    plnCapacity: '2.200 VA',
    plnCustomerId: 'PLN-538812013',
    pamMeterNo: 'PAM-88313',
    pamReadingLastMonth: 40,
    pamReadingThisMonth: 41,
    pamUsage: 1,
    monthlyIplFee: 200000,
    wasteSchedule: 'SENIN_RABU_JUMAT',
    hasBiopori: true,
    hasSolarPanel: false,
    paymentStatus: 'LUNAS',
    notes: 'Unit kosong siap huni / investasi.',
  },
];

// Helper Server Loaders
export async function getInitialResidents(): Promise<ResidentItem[]> {
  return DEFAULT_RESIDENTS;
}

export async function getInitialVehicles(): Promise<VehicleItem[]> {
  try {
    if (process.env.DATABASE_URL) {
      const rows = await neonSql`
        SELECT v.id, v.property_id, v.plate_number, v.type, v.brand, v.model, v.color, v.year, v.is_active,
               p.code as house_code, p.notes as prop_notes,
               (SELECT per.name FROM property_ownerships po 
                JOIN persons per ON po.person_id = per.id 
                WHERE po.property_id = p.id AND po.is_active = true 
                LIMIT 1) as owner_name,
               (SELECT per.name FROM occupancies occ 
                JOIN household_members hm ON occ.household_id = hm.household_id 
                JOIN persons per ON hm.person_id = per.id 
                WHERE occ.property_id = p.id AND occ.is_active = true 
                LIMIT 1) as occupant_name
        FROM vehicles v
        JOIN properties p ON v.property_id = p.id
        WHERE v.is_active = true
        ORDER BY p.code ASC;
      `;

      if (rows && rows.length > 0) {
        return rows.map((r: any, idx: number) => {
          const fallback = DEFAULT_VEHICLES.find(
            dv => dv.plateNumber.toUpperCase() === r.plate_number.toUpperCase() || dv.id === r.id
          );

          const owner = r.occupant_name || r.owner_name || fallback?.ownerName || 'Warga Terdaftar';
          const rfidTag = fallback?.rfidTag || `RFID-782${String(1001 + idx).slice(-4)}`;

          return {
            id: r.id,
            propertyId: r.property_id,
            houseCode: r.house_code || fallback?.houseCode || 'Kav A',
            areaLabel: 'Kavling',
            ownerName: owner,
            plateNumber: r.plate_number,
            type: r.type || fallback?.type || 'Mobil',
            brand: r.brand || fallback?.brand || 'Toyota',
            model: r.model || fallback?.model || '',
            year: Number(r.year) || fallback?.year || 2023,
            color: r.color || fallback?.color || 'Hitam',
            rfidTag: rfidTag,
            gateAccess: fallback?.gateAccess || 'SEMUA_GERBANG',
            rfidStatus: (fallback?.rfidStatus as any) || 'AKTIF',
            notes: fallback?.notes || 'Parkir di kavling',
          };
        });
      }
    }
  } catch (err) {
    console.warn('getInitialVehicles neon fallback:', err);
  }

  return DEFAULT_VEHICLES;
}

export async function getInitialPermits(): Promise<PermitItem[]> {
  return DEFAULT_PERMITS;
}

export async function getInitialUtilities(): Promise<UtilityItem[]> {
  return DEFAULT_UTILITIES;
}
